### ISSUE TITLE
Calculate total score instead of extracting one.

### ISSUE THREAD

**Issue by keke8273** [keke8273/Pikeman#115]

**Comment by keke8273** [comment]
The algorithm only relies on the subject result now. The total results, total ranking, and subject ranking are all calculated on the fly. and it unveiled this problem. 

![image](https://cloud.githubusercontent.com/assets/12285111/18409472/438d5436-778b-11e6-82bd-e19b577c096d.png)

**Comment by mylaluna** [comment]
Client replayed the problematic exam does have a few calculation errors due to the human mistake.
Exams sent to us at the later stage, for example, 2015 to 2016 exams should have a correct calculation.
The formula is 英折（150） = 英语（120）* 1.25
1 digit after the point.

I have let our client know the consequence of incorrect total result. For now, I think we can still use the total results from the spreadsheet.

**Comment by keke8273** [comment]
i dont see there is any advantage changing back to extract the total result now. We already done the work to calculate the total result for each student. It make the app more reliable in the sense that it protect the app from future human errors. The less we extract from the excel spreadsheet, the more flexible the app is. 

If no other concerns will close this issue.

**Comment by mylaluna** [comment]
All right then. Let us calculate the total ourselves.
